steps:
- name: 'ubuntu'
  args: ['echo', 'hello world']
- name: 'ubuntu'
  args: ['find']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'list']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'print-identity-token', '--impersonate-service-account=pub-dev@jonasfj-dart-testing.iam.gserviceaccount.com', '--audiences=https://pub.dev']
