steps:
- name: ubuntu
  script: |
    echo "pwd:"
    pwd
    echo "whoami:"
    whoami
    echo "ls:"
    ls
    echo "files:"
    find
    echo "cd /"
    cd /
    ls
    echo "cd /workspace"
    cd /workspace
    ls
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'print-identity-token', '--impersonate-service-account=pub-dev@jonasfj-dart-testing.iam.gserviceaccount.com', '--audiences=https://pub.dev', '--include-email']


